CREATE TABLE IF NOT EXISTS wsbfi_3_dev.agreement_loan_agreement_raw_today_odps
(
    agreement_id                       VARCHAR(100)
    ,agreement_number                  STRING
    ,branch_id                         INT
    ,application_id                    STRING
    ,customer_cif_id                   STRING
    ,product_id                        INT
    ,package_id                        INT
    ,otr_price                         DOUBLE
    ,down_payment_amount               DOUBLE
    ,ntf_amount                        DOUBLE
    ,funding_amount                    DOUBLE
    ,admin_fee                         DOUBLE
    ,provision_fee                     DOUBLE
    ,fiducia_fee                       DOUBLE
    ,capitalized_ntf_amount            DOUBLE
    ,interest_type                     STRING
    ,flat_rate                         DOUBLE
    ,effective_rate                    DOUBLE
    ,tenor                             INT
    ,tenor_unit                        STRING
    ,admin_fee_type                    STRING
    ,provision_fee_type                STRING
    ,fiducia_fee_type                  STRING
    ,effective_date                    DATE
    ,golive_date                       DATE
    ,maturity_date                     DATE
    ,agreement_date                    DATE
    ,disbursement_date                 DATE
    ,`status`                          STRING
    ,purpose_of_financing              STRING
    ,way_of_financing                  STRING
    ,installment_scheme                STRING
    ,step_up_down_type                 STRING
    ,late_charge_method                STRING
    ,cum_tenor                         INT
    ,installment_allocation_type       STRING
    ,first_installment                 STRING
    ,disbursed_amount                  DOUBLE
    ,disbursed_at                      DATETIME
    ,paid_amount                       DOUBLE
    ,last_paid_at                      DATETIME
    ,created_at                        DATETIME
    ,updated_at                        DATETIME
    ,updated_by                        STRING
    ,deleted_at                        DATETIME
    ,confins_application_id            STRING
    ,incentive_reverse                 DOUBLE
    ,survey_date                       DATE
    ,customer_type                     STRING
    ,beneficiary_account_num           VARCHAR(30)
    ,beneficiary_account_name          STRING
    ,beneficiary_account_bank_id       BIGINT
    ,beneficiary_account_bank_branch   STRING
    ,beneficiary_type                  INT
    ,beneficiary_status                STRING
    ,financing_type_id                 INT
    ,beneficiary_account_bank          STRING
    ,contract_uploaded                 BOOLEAN
    ,confins_published                 BOOLEAN
    ,asset_insurance_calculation_id    STRING
    ,life_insurance_calculation_id     STRING
    ,referral_id                       STRING
    ,surveyor_id                       STRING
    ,assignment_survey_id              STRING
    ,marketing_id                      STRING
    ,credit_insurance_premium          DOUBLE
    ,life_insurance_premium            DOUBLE
    ,asset_insurance_premium           DOUBLE
    ,credit_insurance_calculation_id   STRING
    ,other_fee                         DOUBLE
    ,other_fee_type                    STRING
    ,confins_beneficiary_id            STRING
    ,santunan_insurance_premium        DOUBLE
    ,santunan_insurance_calculation_id STRING
    ,rsa_insurance_calculation_id      STRING
    ,rsa_insurance_premium             DOUBLE
    ,split_funding                     STRING
    ,is_multiple_beneficiaries         BOOLEAN
    ,beneficiary_amount                DOUBLE
    ,deleted                           BOOLEAN
    ,maintenance_committed             BOOLEAN
    ,maintenance_committed_at          DATETIME
    ,hold_status                       BOOLEAN
    ,source_ts_ms                      DATETIME
    ,operation_ts_ms                   DATETIME
    ,is_deleted                        BOOLEAN
    ,op                                VARCHAR(5)
    ,inserted_date                     DATETIME
    ,pos_id                            STRING
    ,default_status                    STRING
    ,restructured                      BOOLEAN
    ,restructured_at                   DATETIME
    ,non_accrual_at                    DATETIME
    ,written_off_at                    DATETIME
    ,asset_insurance_type              STRING
    ,life_insurance_type               STRING
    ,credit_insurance_type             STRING
    ,santunan_insurance_type           STRING
    ,rsa_insurance_type                STRING
    ,parent_agreement_id               VARCHAR(100)
    ,restructured_partial_paid         DOUBLE
    ,credit_type                       STRING
    ,channel                           STRING
    ,currency                          STRING
    ,first_due_date                    DATE
    ,last_due_date                     DATE
    ,approval_date                     DATE
    ,allocation_scheme_id              STRING
    ,is_auto_golive                    BOOLEAN
    ,soa_id                            DOUBLE
    ,supplier_rate                     DOUBLE
    ,activity_id                       STRING
    ,media_id                          STRING
    ,default_status_description        STRING
    ,workflow                          STRING
    ,marketing_id_2                    STRING
    ,is_potong_funding                 STRING
    ,application_id_potong_funding     STRING
    ,expiration_date_of_agreement      DATE
    ,cancellation_date                 DATETIME
    ,finance_type                      STRING
    ,is_insurance_transfer             BOOLEAN
    ,old_agreement_number              STRING
    ,inventory_date                    DATETIME
    ,net_yield                         DOUBLE
    ,adjusted_effective_rate           DOUBLE
    ,has_collateral                    BOOLEAN
    ,insurance_length                  INT
    ,guarantor_cif_ids                 STRING
    ,financial_company_id              BIGINT
    ,financial_company_code            STRING
    ,agreement_rating                  STRING
    ,customer_group_exposure           DOUBLE
    ,accrued_interest_amount           DOUBLE
    ,accrued_interest_type             STRING
    ,ready_release_document_at         DATETIME
    ,spread_rate                       DOUBLE
    ,incentive_reserve                 DOUBLE
    ,grace_period_length               INT
    ,grace_period_type                 STRING
    ,reference_customer_id             STRING
    ,mou_id                            VARCHAR(255)
    ,floating_period_review            STRING
    ,floating_reference_rate_code      STRING
    ,start_floating_sequence           DOUBLE
    ,latest_floating_rate              DOUBLE
    ,is_digital_signing                BOOLEAN
    ,application_source                STRING
    ,created_by                        STRING
    ,sub_branch_id                     STRING
    ,termin_number                     INT
    ,product_scheme                    STRING
    ,agreement_rating_code             STRING
    ,agreement_number_potong_funding   STRING
) STORED AS ALIORC TBLPROPERTIES ('columnar.nested.type'='true', 'comment'='agreement_loan_agreement');
