CREATE TABLE IF NOT EXISTS wsbfi_3_dev.ar_agrmnt_raw_today_odps
(
    agrmnt_id                     BIGINT
    ,cwr_no                       VARCHAR(100)
    ,curr_code                    VARCHAR(50)
    ,office_code                  VARCHAR(50)
    ,agrmnt_no                    VARCHAR(100)
    ,cust_no                      VARCHAR(100)
    ,spouse_no                    VARCHAR(100)
    ,num_of_asset                 INT
    ,tenor                        INT
    ,pay_freq_code                VARCHAR(50)
    ,num_of_inst                  INT
    ,cumulative_tenor             INT
    ,interest_type                VARCHAR(50)
    ,inst_scheme                  VARCHAR(50)
    ,step_up_down_type            VARCHAR(50)
    ,grace_period_lc              INT
    ,mr_lc_calc_method_code       VARCHAR(50)
    ,total_asset_price            DOUBLE
    ,total_down_payment_gross_amt DOUBLE
    ,total_down_payment_nett_amt  DOUBLE
    ,ntf_amt                      DOUBLE
    ,ins_capitalized_amt          DOUBLE
    ,os_principal_undue_amt       DOUBLE
    ,os_interest_undue_amt        DOUBLE
    ,os_principal_amt             DOUBLE
    ,os_interest_amt              DOUBLE
    ,tdp_paid_coy_amt             DOUBLE
    ,diff_rate_amt                DOUBLE
    ,next_inst_due_num            INT
    ,next_inst_num                INT
    ,next_inst_due_dt             DATE
    ,next_inst_dt                 DATE
    ,next_inst_amt                DOUBLE
    ,contract_stat_code           VARCHAR(50)
    ,default_stat_code            VARCHAR(50)
    ,agrmnt_dt                    DATE
    ,go_live_dt                   DATE
    ,go_live_by                   VARCHAR(50)
    ,pre_go_live_dt               DATE
    ,effective_dt                 DATE
    ,maturity_dt                  DATE
    ,prepaid_hold_stat_code       VARCHAR(50)
    ,lc_inst_rate_prml            DOUBLE
    ,lc_ins_rate_prml             DOUBLE
    ,effective_rate_prcnt         DOUBLE
    ,flat_rate_prcnt              DOUBLE
    ,grace_period                 INT
    ,grace_period_type            VARCHAR(50)
    ,mr_first_inst_type_code      VARCHAR(50)
    ,notes                        VARCHAR(4000)
    ,lbppms_clctblty_code         VARCHAR(50)
    ,app_no                       VARCHAR(50)
    ,prod_offering_code           VARCHAR(50)
    ,prod_offering_version        VARCHAR(20)
    ,virtual_acc_no               VARCHAR(100)
    ,mr_wop_code                  VARCHAR(50)
    ,inst_amt                     DOUBLE
    ,floating_next_review_dt      DATE
    ,start_floating_inst          INT
    ,ref_prod_type_code           VARCHAR(50)
    ,lob_code                     VARCHAR(50)
    ,is_coll_block                BOOLEAN
    ,baloon_value_amt             DOUBLE
    ,lc_inst_admin_fee_amt        DOUBLE
    ,floating_period_code         VARCHAR(50)
    ,journal_no                   VARCHAR(100)
    ,biz_template_code            VARCHAR(50)
    ,lms_schm_h_id                BIGINT
    ,exp_dt                       DATE
    ,inst_rounding                DOUBLE
    ,final_gross_yield_prcnt      DOUBLE
    ,usr_crt                      VARCHAR(50)
    ,usr_upd                      VARCHAR(50)
    ,dtm_crt                      DATETIME
    ,dtm_upd                      DATETIME
    ,integrity_value              VARCHAR(500)
    ,gross_yield_prcnt            DOUBLE
    ,cwr_version                  BIGINT
    ,total_income_amt             DOUBLE
    ,total_recog_amt              DOUBLE
    ,last_amendment_effective_dt  DATE
    ,interest_paid_amt            DOUBLE
    ,principal_paid_amt           DOUBLE
    ,floating_margin_rate_prcnt   DOUBLE
    ,floating_ref_rate_code       VARCHAR(50)
    ,source_ts_ms                 DATETIME
    ,operation_ts_ms              DATETIME
    ,is_deleted                   BOOLEAN
    ,op                           VARCHAR(5)
    ,inserted_date                DATETIME
) STORED AS ALIORC TBLPROPERTIES ('columnar.nested.type'='true', 'comment'='ar_agrmnt');
