CREATE TABLE IF NOT EXISTS wsbfi_3_dev.customer_cif_raw_today_odps
(
    cif_id                            VARCHAR(100)
    ,name                             STRING
    ,id_type                          STRING
    ,id_number                        STRING
    ,mobile_phone                     STRING
    ,email                            STRING
    ,birth_date                       DATE
    ,birth_place                      STRING
    ,mother_name                      STRING
    ,occupation                       STRING
    ,occupation_id                    STRING
    ,spouse_name                      STRING
    ,spouse_id_number                 STRING
    ,spouse_birth_date                DATE
    ,spouse_birth_place               STRING
    ,spouse_occupation                STRING
    ,spouse_occupation_id             STRING
    ,customer_group_id                STRING
    ,customer_type                    STRING
    ,monthly_income                   DOUBLE
    ,num_dependent                    INT
    ,emergency_relation               STRING
    ,emergency_name                   STRING
    ,emergency_number                 STRING
    ,created_at                       DATETIME
    ,updated_at                       DATETIME
    ,updated_by                       STRING
    ,deleted_at                       DATETIME
    ,npwp                             VARCHAR(20)
    ,gender                           STRING
    ,confins_customer_id              STRING
    ,profession_id                    STRING
    ,profession_mapping_id            STRING
    ,personal_customer_type           STRING
    ,education_id                     BIGINT
    ,industry_type_id                 BIGINT
    ,home_status_id                   BIGINT
    ,religion_id                      BIGINT
    ,marital_status_id                BIGINT
    ,company_name                     STRING
    ,legal_name                       STRING
    ,spouse_legal_name                STRING
    ,deleted                          BOOLEAN
    ,source_ts_ms                     DATETIME
    ,operation_ts_ms                  DATETIME
    ,is_deleted                       BOOLEAN
    ,op                               VARCHAR(5)
    ,inserted_date                    DATETIME
    ,npwp_type                        STRING
    ,spouse_mobile_phone              STRING
    ,home_owner_name                  STRING
    ,old_npwp                         STRING
    ,employment_since_year            STRING
    ,other_income                     DOUBLE
    ,turnover                         DOUBLE
    ,stay_since_year                  STRING
    ,home_location                    STRING
    ,home_price                       STRING
    ,spouse_income                    DOUBLE
    ,number_of_employees              DOUBLE
    ,monthly_variable_income          DOUBLE
    ,nationality                      STRING
    ,id_number_expiration_date        DATE
    ,spouse_occupation_status         STRING
    ,sources_of_income                STRING
    ,is_guarantor                     BOOLEAN
    ,occupation_status                STRING
    ,spouse_id_number_expiration_date DATE
    ,is_split_treasure                BOOLEAN
) STORED AS ALIORC TBLPROPERTIES ('comment'='customer_cif');
