CREATE TABLE bravo_sit.backoffice_application
(
    id character varying(255),
    product_id INTEGER,
    group_id character varying(255),
    status text,
    branch_id INTEGER,
    branch_name text,
    customer_name text,
    supplier_id text,
    supplier_name text,
    supplier_commission_completed_date_time timestamp without time zone,
    asset_validation_completed_date_time timestamp without time zone,
    funding_document_completed_date_time timestamp without time zone,
    po_ready_for_approval_date_time timestamp without time zone,
    po_document_approved_date_time timestamp without time zone,
    asset_validation_message text,
    funding_document_message text,
    asset_full_name text,
    ntf numeric(38,18),
    tdp numeric(38,18),
    vehicle_price numeric(38,18),
    initial_marketing_id text,
    initial_marketing_spv_id text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    po_document_id text,
    refund_insurance_amount numeric(38,18),
    refund_interest_amount numeric(38,18),
    is_restructure BOOLEAN,
    bravo_agent_id text,
    customer_nik text,
    bravo_agent_name text,
    source_ts_ms TIMESTAMP,
    operation_ts_ms TIMESTAMP,
    is_deleted BOOLEAN,
    op VARCHAR(5),
    inserted_date TIMESTAMP
    ,PRIMARY KEY (id)
);